site_name: EchoSphere
site_url: https://mauricekuenicke.github.io/EchoSphere/
site_author: Maurice Künicke
edit_uri: edit/main/docs/
repo_url: https://github.com/MauriceKuenicke/EchoSphere
repo_name: MauriceKuenicke/EchoSphere
theme:
  icon:
    logo: material/sphere
    repo: fontawesome/brands/github

  language: en

  name: material
  custom_dir: docs/overrides

  font:
    text: Nunito

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - search.suggest
    - search.share
    - search.highlight
    - content.code.copy

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/index.md
  - User Guide:
      - Overview: user-guide/index.md
      - Writing Tests: writing-tests/index.md
      - Command Reference: command-reference/index.md
  - Reference:
      - Configuration: reference/configuration.md
      - Environment Variables: reference/environment-variables.md
      - SQL Testing Syntax: reference/sql-testing-syntax.md
      - API Usage: reference/api-usage.md
  - Advanced Topics:
      - CI/CD Integration: advanced/ci-cd.md
      - Performance: advanced/performance.md
      - Large-Scale Management: advanced/large-scale.md
  - Examples & Tutorials:
      - Cookbook: examples/cookbook.md
  - Troubleshooting: troubleshooting/index.md
  - Contributing: contributing.md

copyright: Copyright &copy; 2025 - Maurice Künicke

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MauriceKuenicke
      name: Maurice on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/maurice-k%C3%BCnicke-429a211a3/
      name: Maurice on LinkedIn

markdown_extensions:
  - abbr
  - admonition
  - attr_list